version: '2.1'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  ksql-server:
    image: confluentinc/cp-ksql-server:5.0.1
    hostname: ksql-server
    depends_on:
      - kafka
      - connect_source
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_HOST_NAME: ksql-server
      KSQL_APPLICATION_ID: "streaming-aggregates-ddd"
      APPLICATION_ID: "streaming-aggregates-ddd"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
  ksql-cli:
    image: confluentinc/cp-ksql-cli:5.0.1
    depends_on:
      - kafka
      - connect_source
      - ksql-server
      - aggregator
    entrypoint: /bin/sh
    tty: true
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  mongodb:
    image: mongo:latest
    ports:
     - 27017:27017
  connect_source:
    image: debezium/connect:${DEBEZIUM_VERSION}
    build:
      context: debezium-mongodb
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_source_connect_configs
     - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
  connect_sink:
    image: debezium/connect-mongodb:${DEBEZIUM_VERSION}
    build:
      context: debezium-mongodb
    ports:
     - 8084:8083
    links:
     - kafka
     - mongodb
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=2
     - CONFIG_STORAGE_TOPIC=my_sink_connect_configs
     - OFFSET_STORAGE_TOPIC=my_sink_connect_offsets
     - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
     - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
  aggregator:
    image: debezium/kstreams-aggregator:${DEBEZIUM_VERSION}
    build:
      context: poc-ddd-aggregates
    links:
     - kafka
    environment:
     - JAVA_MAIN_CLASS=io.debezium.examples.aggregation.StreamingAggregatesDDD
     - PARENT_TOPIC=dbserver1.inventory.customers
     - CHILDREN_TOPIC=dbserver1.inventory.addresses
     - BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
     - connect_source
    command: >
      /bin/bash -c "
        while ! curl -f -s -X GET http://connect_source:8083/connectors/mysql-source;
        do
          echo 'Waiting for source connector to be deployed';
          sleep 1;
        done;
        echo 'Source connector deployed!';
        /opt/poc-ddd-aggregates/run-aggregator.sh
      "
